google-oauth-client: optimize refreshing of access token
clouway/oauth2-java-client pull request #2
Opened 2017-12-08 16:16 UTC by qnislavnachev

now before refreshing access token expiration time is checked
instead of send request for token info.

additional fixes: readme.md updated and add implemebtation
of CredentialsStore to save credentials in local file

2017-12-08 19:54 UTC, mgenov requested changes

2017-12-08 19:54 UTC, mgenov commented on oauth2-java-client-console/src/main/java/com/clouway/oauth2/client/ConsoleAppTokenSource.kt
> +        if (credentials.expirationDateInMilis < date.time) {
Refresh may also fail.

2017-12-08 19:54 UTC, mgenov commented on oauth2-java-client-console/src/test/java/com/clouway/oauth2/client/adapter/http/google/LocalCredentialsFileStorageTest.kt
> +class LocalCredentialsFileStorageTest {
JUnit has TemporaryFolder rule for this kind of tests. It will ensure that temp folder will be removed.

2017-12-08 19:54 UTC, mgenov commented on README.md
> +##### Generate access token by google oauth server using console app
Using Google Auth Server for Offline Apps

2017-12-11 09:11 UTC, qnislavnachev commented on oauth2-java-client-console/src/test/java/com/clouway/oauth2/client/adapter/http/google/LocalCredentialsFileStorageTest.kt
> +class LocalCredentialsFileStorageTest {
will be implemented

2017-12-11 09:11 UTC, qnislavnachev commented on oauth2-java-client-console/src/main/java/com/clouway/oauth2/client/ConsoleAppTokenSource.kt
> +        if (credentials.expirationDateInMilis < date.time) {
will be fixed

2017-12-11 09:12 UTC, qnislavnachev commented on README.md
> +##### Generate access token by google oauth server using console app
will be updated

2017-12-11 09:22 UTC, mgenov commented on oauth2-java-client-console/src/test/java/com/clouway/oauth2/client/adapter/http/google/LocalCredentialsFileStorageTest.kt
> +        val credentialsStorage = LocalCredentialsFileStorage(tempFolder.root.path + "/test")
This concatenations are looking bad. 

http://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html#newFile(java.lang.String)

2017-12-11 09:31 UTC, mlesikov commented on README.md
> +String accessToken = tokenSource.getToken();
you can continue with
```
or 
Credentials = GogogleOauthServerCredentialsFactory.create(config)
```

we can add a factory that will be easier to use.

What do you think

2017-12-11 09:31 UTC, mlesikov commented on README.md
> +OAuthClient oauthClient = GoogleOAuthClient(config.getClient(), config.getSecret(), NetHttpTransport());
OAuthClient here is not a good name because it is use  in another context on the upper level in this example

2017-12-11 09:33 UTC, qnislavnachev commented on oauth2-java-client-console/src/test/java/com/clouway/oauth2/client/adapter/http/google/LocalCredentialsFileStorageTest.kt
> +        val credentialsStorage = LocalCredentialsFileStorage(tempFolder.root.path + "/test")
will be fixed File will be passed to the constructor instead of path

2017-12-11 09:34 UTC, qnislavnachev commented on README.md
> +String accessToken = tokenSource.getToken();
it seems reasonable we can do that

2017-12-11 09:35 UTC, qnislavnachev commented on README.md
> +OAuthClient oauthClient = GoogleOAuthClient(config.getClient(), config.getSecret(), NetHttpTransport());
I am going to rename it to OAuthHttpClient. Is that name sounds good to you ?

2017-12-11 09:54 UTC, mlesikov commented on README.md
> +OAuthClient oauthClient = GoogleOAuthClient(config.getClient(), config.getSecret(), NetHttpTransport());
It is better

2017-12-11 11:14 UTC, qnislavnachev commented
Testing with TemporaryFolder() fixed, renamed some classes, added wrapper class for generating credentials. PR notes are fixed need another review

2017-12-11 11:39 UTC, mgenov approved these changes
LGTM !

2017-12-11 11:39 UTC, merged